clear all;
clc;
close all;

%% Parameters
T_inside = zeros(24,1); %C
for i = 1:1:24
    T_inside(i) =20;
end

UA = 0.7;      %kW
T_outside = [-5;-5;-5;-5;-5;-5;2;2;2;2;2;2;7;7;7;7;7;7;0;0;0;0;0;0];
days = 8*30;
hours = 24*days;
costEHeater = 150; %$/kW
costElectricity = 0.08; %$/kWh
effEHeater = 0.98; 
BC_CO2 = 50;
AB_CO2 = 1000;
ON_CO2 =30;

%% Part 1

Qloss = zeros(24,1);
%the heat loss during one day
for i = 1:1:24
    Qloss(i) = UA*(T_inside(i)-T_outside(i));
end
QlossDay = sum(Qloss,'All');

QlossTot = QlossDay*days;
PowerConsumption1 = QlossTot/effEHeater;

%Plotting power consumption over days
%figure
%plot(PowerConsumption1);
%xlabel('Days');
%ylabel('Power consumption1(kW)');

%The cost of operating the heater
HeaterMoney = sum(PowerConsumption1,'all')*costEHeater;

%The energy consumption
EnergyTot1 = PowerConsumption1*hours;
ElectricMoney1 = costElectricity*sum(EnergyTot1,'all');

%BC -AB -ON comparision
BC_Sc1_Co2 =  BC_CO2* sum(EnergyTot1,'all');
AB_Sc1_Co2 =  AB_CO2*sum(EnergyTot1,'all');
ON_Sc1_Co2 = ON_CO2*sum(EnergyTot1,'all');

%% Part 2

%Parameters
COP_Carnot  =0.7;
COP_HP  = zeros(24,1);
costHP = 2000 ;%$/kW

for i=1:1:24
    COP_HP(i) = COP_Carnot/(1- (T_outside(i)+273.2)/(20+273.2));
end
WorkCompressor = Qloss;

for i = 1:1:24
    WorkCompressor(i) = Qloss(i)/COP_HP(i);
end
WorkCompressorPerDay =sum(WorkCompressor,'All');

%The cost of heat pump
WorkCompressorTot = WorkCompressorPerDay*days;
HPMoney =  WorkCompressorTot*costHP;
%the electricity cost
EnergyConsumption2 = WorkCompressorPerDay*hours;
ElectricMoney2 = costElectricity*EnergyConsumption2;

%BC -AB -ON comparision



%% Part 3

%Solar Panel properties
n_PV =0.17;
n_heatAmbient =0.7;
A = 20:10:120; %m2
costPV = 100; % $/m2
%PCM properties
h_sl = 155; %kh/kg
Tm =10; 
rho = 1470; %kg/m3
manufactPCMcost = 450; %$/m3
PCMcost =4; %$/kg
SF =1.2; %safety factor for PCM material

%Analysis

%for day time from 6am-6pm, there will be electricity and heat generated by the
%solar panel
ElectricityWorkPV = n_PV*0.5*A;
HeatGeneratedPV = (1-n_PV)*n_heatAmbient*0.5*A;
Qloss3 = zeros(24,1);
for i =1:1:24
    Qloss3(i) =  UA*(T_inside(i)-10);
end

HeatEnergyPVinDay = HeatGeneratedPV*12;  %etotal energy per day of a PV
Mass_TES = HeatEnergyPVinDay/h_sl*SF;    %the mass of PCM material
PCM_Price = Mass_TES*PCMcost;            % cost of PCM material
PCM_Manu_Price =manufactPCMcost*Mass_TES/rho; %cost of manufacturing PCM
PV_Price = A*costPV;                     %cost of solar panel
ElectricityEnergyPVinDayTime= ElectricityWorkPV*12;

%Coefficient of heat pump
COP_HP_day = COP_Carnot/(1- (10+273.2)/(20+273.2));

%the required work to operate the heatpump
WorkCompressor3 = zeros(24,1);
for i = 1:1:24
    WorkCompressor3(i) = Qloss3(i)/COP_HP_day;
end
WorkCompressor3PerDayTime = sum(WorkCompressor3,'All');
WorkCompressorSc3Tot = WorkCompressor3PerDayTime*days;
%money required to consume electricity for the heat pump is
ElectricMoney3 = WorkCompressorSc3Tot*costElectricity;
%The cost of operating the heater
HP_Sc3_Money=  WorkCompressorSc3Tot*costHP;
%The money gain from generating electricity perday from the PV
MoneyElectricGainPerDay = ElectricityEnergyPVinDayTime*costElectricity*days;
DeltaElectrical = MoneyElectricGainPerDay;

for i = 1:1:11
   DeltaElectrical(i) = ElectricMoney3 - MoneyElectricGainPerDay(i);
end
%For a year the annual cost for electricity is
ElectricMoneySc3Tot = DeltaElectrical*days;
















    



 














